- name: variables from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print from files
    ansible.builtin.debug:
      msg: "i am learning {{COURSE}} , course duration is {{DURATION}} and trainer is {{TRAINER}}"